In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

df = pd.read_csv('sementara-100.log',sep='\s+',header=None)
df[6] = df[1]+' '+df[2]

waktu2time = lambda z: datetime.strptime(z,'%Y-%m-%d %H:%M:%S')
df[7] = df[6].apply(waktu2time)

weather = df.loc[:,[7,3,4,5]]

bdg7 = weather[weather[3].isin(['IBANDUNG7'])]
bdg7
# bdg7.set_axis('7').plot()

# df = pd.DataFrame([bdg7[4],bdg7[5]], index=pd.date_range('1/1/2000', periods=2))

# df = df.cumsum()

# plt.figure()
# df.plot()
# plt.show()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>7</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>2018-04-14 06:25:24</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2018-04-14 06:25:54</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.4</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2018-04-14 06:26:24</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.4</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2018-04-14 06:26:31</td>
      <td>IBANDUNG7</td>
      <td>75.02</td>
      <td>75.8</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2018-04-14 06:26:53</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.3</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2018-04-14 06:27:00</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>73.1</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2018-04-14 06:27:00</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>73.6</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2018-04-14 06:27:01</td>
      <td>IBANDUNG7</td>
      <td>75.02</td>
      <td>76.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>2018-04-14 06:27:23</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.3</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2018-04-14 06:27:53</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.3</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2018-04-14 06:28:24</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.3</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2018-04-14 06:28:40</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>73.6</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2018-04-14 06:28:40</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>73.1</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2018-04-14 06:28:54</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.3</td>
    </tr>
    <tr>
      <th>29</th>
      <td>2018-04-14 06:29:23</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.4</td>
    </tr>
    <tr>
      <th>30</th>
      <td>2018-04-14 06:29:53</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.2</td>
    </tr>
    <tr>
      <th>32</th>
      <td>2018-04-14 06:30:23</td>
      <td>IBANDUNG7</td>
      <td>74.66</td>
      <td>75.9</td>
    </tr>
    <tr>
      <th>35</th>
      <td>2018-04-14 06:30:54</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>76.0</td>
    </tr>
    <tr>
      <th>39</th>
      <td>2018-04-14 06:31:24</td>
      <td>IBANDUNG7</td>
      <td>74.84</td>
      <td>76.4</td>
    </tr>
    <tr>
      <th>41</th>
      <td>2018-04-14 06:31:54</td>
      <td>IBANDUNG7</td>
      <td>74.66</td>
      <td>76.4</td>
    </tr>
    <tr>
      <th>43</th>
      <td>2018-04-14 06:32:24</td>
      <td>IBANDUNG7</td>
      <td>74.66</td>
      <td>76.2</td>
    </tr>
    <tr>
      <th>44</th>
      <td>2018-04-14 06:32:54</td>
      <td>IBANDUNG7</td>
      <td>74.66</td>
      <td>75.9</td>
    </tr>
    <tr>
      <th>48</th>
      <td>2018-04-14 06:33:24</td>
      <td>IBANDUNG7</td>
      <td>74.66</td>
      <td>76.4</td>
    </tr>
    <tr>
      <th>51</th>
      <td>2018-04-14 06:33:40</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>73.0</td>
    </tr>
    <tr>
      <th>53</th>
      <td>2018-04-14 06:33:40</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.8</td>
    </tr>
    <tr>
      <th>55</th>
      <td>2018-04-14 06:33:40</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.9</td>
    </tr>
    <tr>
      <th>57</th>
      <td>2018-04-14 06:33:54</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>75.7</td>
    </tr>
    <tr>
      <th>58</th>
      <td>2018-04-14 06:34:25</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>75.5</td>
    </tr>
    <tr>
      <th>60</th>
      <td>2018-04-14 06:34:54</td>
      <td>IBANDUNG7</td>
      <td>74.48</td>
      <td>75.7</td>
    </tr>
    <tr>
      <th>63</th>
      <td>2018-04-14 06:35:20</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.8</td>
    </tr>
    <tr>
      <th>64</th>
      <td>2018-04-14 06:35:20</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.9</td>
    </tr>
    <tr>
      <th>65</th>
      <td>2018-04-14 06:35:20</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>73.0</td>
    </tr>
    <tr>
      <th>68</th>
      <td>2018-04-14 06:35:24</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>75.7</td>
    </tr>
    <tr>
      <th>72</th>
      <td>2018-04-14 06:35:54</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>75.8</td>
    </tr>
    <tr>
      <th>73</th>
      <td>2018-04-14 06:36:24</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>76.0</td>
    </tr>
    <tr>
      <th>74</th>
      <td>2018-04-14 06:36:54</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>76.0</td>
    </tr>
    <tr>
      <th>79</th>
      <td>2018-04-14 06:37:24</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>75.9</td>
    </tr>
    <tr>
      <th>80</th>
      <td>2018-04-14 06:37:54</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>75.8</td>
    </tr>
    <tr>
      <th>82</th>
      <td>2018-04-14 06:38:24</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>75.8</td>
    </tr>
    <tr>
      <th>83</th>
      <td>2018-04-14 06:38:54</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>76.0</td>
    </tr>
    <tr>
      <th>87</th>
      <td>2018-04-14 06:39:24</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>76.1</td>
    </tr>
    <tr>
      <th>88</th>
      <td>2018-04-14 06:39:54</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>76.1</td>
    </tr>
    <tr>
      <th>92</th>
      <td>2018-04-14 06:40:20</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.7</td>
    </tr>
    <tr>
      <th>93</th>
      <td>2018-04-14 06:40:20</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.5</td>
    </tr>
    <tr>
      <th>94</th>
      <td>2018-04-14 06:40:20</td>
      <td>IBANDUNG7</td>
      <td>74.30</td>
      <td>72.7</td>
    </tr>
    <tr>
      <th>96</th>
      <td>2018-04-14 06:40:24</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>76.1</td>
    </tr>
    <tr>
      <th>97</th>
      <td>2018-04-14 06:40:54</td>
      <td>IBANDUNG7</td>
      <td>74.12</td>
      <td>76.8</td>
    </tr>
  </tbody>
</table>
</div>

In [ ]:
print("TESET")

TEST